"""initial schema

Revision ID: 7cc317828efa
Revises: 
Create Date: 2026-05-15 23:51:58.956606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cc317828efa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.Enum('user_agreement', 'privacy_policy', 'personal_data_consent', name='legal_document_type'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_legal_documents_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type')
    )
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.create_index('ix_legal_documents_document_type', ['document_type'], unique=False)
        batch_op.create_index('ix_legal_documents_uploaded_at', ['uploaded_at'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=30), server_default='user', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('organization_description', sa.String(length=3000), nullable=True),
    sa.Column('legal_documents_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('legal_documents_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index('ix_users_is_blocked', ['is_blocked'], unique=False)
        batch_op.create_index('ix_users_legal_documents_accepted', ['legal_documents_accepted'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organizer_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_format', sa.Enum('offline', 'online', name='event_format'), server_default='offline', nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('participant_requirements', sa.Text(), nullable=True),
    sa.Column('registration_type', sa.Enum('internal', 'external', 'none', name='event_registration_type'), nullable=False),
    sa.Column('registration_confirmation', sa.String(length=20), nullable=True),
    sa.Column('external_registration_url', sa.String(length=1000), nullable=True),
    sa.Column('price_type', sa.Enum('free', 'fixed', 'from', name='event_price_type'), server_default='free', nullable=False),
    sa.Column('price_value', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('published', 'blocked', 'on_review', 'archived', name='event_status'), server_default='published', nullable=False),
    sa.Column('organizer_complaint_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("price_type = 'free' OR price_value IS NOT NULL", name='ck_events_paid_price_required'),
    sa.CheckConstraint("registration_type <> 'external' OR external_registration_url IS NOT NULL", name='ck_events_external_url_required'),
    sa.CheckConstraint("registration_type <> 'internal' OR registration_confirmation IS NOT NULL", name='ck_events_internal_confirmation_required'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_events_event_datetime', ['event_datetime'], unique=False)
        batch_op.create_index('ix_events_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('ix_events_registration_type', ['registration_type'], unique=False)
        batch_op.create_index('ix_events_status', ['status'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('organizer_ratings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organizer_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_organizer_ratings_rating_range'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'user_id', name='uq_organizer_ratings_organizer_user')
    )
    with op.batch_alter_table('organizer_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_organizer_ratings_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('ix_organizer_ratings_rating', ['rating'], unique=False)
        batch_op.create_index('ix_organizer_ratings_user_id', ['user_id'], unique=False)

    op.create_table('event_complaints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('complaint_type', sa.Enum('misinformation', 'fraud', 'prohibited_content', 'duplicate', 'other', name='event_complaint_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('organizer_comment', sa.Text(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'reporter_id', name='uq_event_complaints_event_reporter')
    )
    with op.batch_alter_table('event_complaints', schema=None) as batch_op:
        batch_op.create_index('ix_event_complaints_complaint_type', ['complaint_type'], unique=False)
        batch_op.create_index('ix_event_complaints_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_complaints_last_changed_at', ['last_changed_at'], unique=False)
        batch_op.create_index('ix_event_complaints_reporter_id', ['reporter_id'], unique=False)

    op.create_table('event_registration_fields',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'email', 'phone', 'number', 'date', 'select', 'textarea', 'checkbox', name='registration_field_type'), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_registration_fields', schema=None) as batch_op:
        batch_op.create_index('ix_event_registration_fields_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_registration_fields_sort_order', ['sort_order'], unique=False)

    op.create_table('event_registrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'registered', 'rejected', 'canceled', name='registration_status'), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_registrations_event_user')
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index('ix_event_registrations_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_registrations_status', ['status'], unique=False)
        batch_op.create_index('ix_event_registrations_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('ix_event_registrations_user_id', ['user_id'], unique=False)

    op.create_table('event_reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_event_reviews_rating_range'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_reviews_event_user')
    )
    with op.batch_alter_table('event_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_event_reviews_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_event_reviews_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_reviews_is_hidden', ['is_hidden'], unique=False)
        batch_op.create_index('ix_event_reviews_rating', ['rating'], unique=False)
        batch_op.create_index('ix_event_reviews_user_id', ['user_id'], unique=False)

    op.create_table('event_tags',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id')
    )
    with op.batch_alter_table('event_tags', schema=None) as batch_op:
        batch_op.create_index('ix_event_tags_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index('ix_favorites_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_favorites_user_id', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('organizer_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=1000), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_notifications_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_notifications_notification_type', ['notification_type'], unique=False)
        batch_op.create_index('ix_notifications_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    op.create_table('review_complaints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['event_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'reporter_id', name='uq_review_complaints_review_reporter')
    )
    with op.batch_alter_table('review_complaints', schema=None) as batch_op:
        batch_op.create_index('ix_review_complaints_last_changed_at', ['last_changed_at'], unique=False)
        batch_op.create_index('ix_review_complaints_reporter_id', ['reporter_id'], unique=False)
        batch_op.create_index('ix_review_complaints_review_id', ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_review_complaints_review_id')
        batch_op.drop_index('ix_review_complaints_reporter_id')
        batch_op.drop_index('ix_review_complaints_last_changed_at')

    op.drop_table('review_complaints')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id')
        batch_op.drop_index('ix_notifications_organizer_id')
        batch_op.drop_index('ix_notifications_notification_type')
        batch_op.drop_index('ix_notifications_is_read')
        batch_op.drop_index('ix_notifications_event_id')
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_favorites_user_id')
        batch_op.drop_index('ix_favorites_event_id')

    op.drop_table('favorites')
    with op.batch_alter_table('event_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_event_tags_tag_id')
        batch_op.drop_index('ix_event_tags_event_id')

    op.drop_table('event_tags')
    with op.batch_alter_table('event_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_event_reviews_user_id')
        batch_op.drop_index('ix_event_reviews_rating')
        batch_op.drop_index('ix_event_reviews_is_hidden')
        batch_op.drop_index('ix_event_reviews_event_id')
        batch_op.drop_index('ix_event_reviews_created_at')

    op.drop_table('event_reviews')
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index('ix_event_registrations_user_id')
        batch_op.drop_index('ix_event_registrations_submitted_at')
        batch_op.drop_index('ix_event_registrations_status')
        batch_op.drop_index('ix_event_registrations_event_id')

    op.drop_table('event_registrations')
    with op.batch_alter_table('event_registration_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_event_registration_fields_sort_order')
        batch_op.drop_index('ix_event_registration_fields_event_id')

    op.drop_table('event_registration_fields')
    with op.batch_alter_table('event_complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_event_complaints_reporter_id')
        batch_op.drop_index('ix_event_complaints_last_changed_at')
        batch_op.drop_index('ix_event_complaints_event_id')
        batch_op.drop_index('ix_event_complaints_complaint_type')

    op.drop_table('event_complaints')
    with op.batch_alter_table('organizer_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_organizer_ratings_user_id')
        batch_op.drop_index('ix_organizer_ratings_rating')
        batch_op.drop_index('ix_organizer_ratings_organizer_id')

    op.drop_table('organizer_ratings')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_files_entity_type'))
        batch_op.drop_index(batch_op.f('ix_files_entity_id'))
        batch_op.drop_index('ix_files_entity')

    op.drop_table('files')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_status')
        batch_op.drop_index('ix_events_registration_type')
        batch_op.drop_index('ix_events_organizer_id')
        batch_op.drop_index('ix_events_event_datetime')
        batch_op.drop_index('ix_events_created_at')

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_legal_documents_accepted')
        batch_op.drop_index('ix_users_is_blocked')
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_name')

    op.drop_table('tags')
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_legal_documents_uploaded_at')
        batch_op.drop_index('ix_legal_documents_document_type')

    op.drop_table('legal_documents')
    # ### end Alembic commands ###
